-- ----------------------------------
-- DES720 Week 6
-- Clint MacDonald
-- Feb. 11, 2025
-- DDL - Creation Scripts
-- ----------------------------------

-- DML, DDL, TCL
-- DDL - Data Defination Language

-- CREATE OR REPLACE VIEW was already covered.
-- CREATE, ALTER, and DROP

-- ----------------------
-- Creating Tables

-- Constraints
-- 7 Constraints will cover 99% of the work you need to do.

/*
PRIMARY KEY - obvious
FOREIGN KEY - enforcement of Referential Integrity
DEFAULT     - sets the default value if null is inserted
UNIQUE      - all rows must contain a unique value
required (NOT NULL) - insert of a null value is not permitted
range (CHECK) - placing range limitations on values
INDEX       - allowing the database to presort data by the column (optimization)
*/

/* CREATE TABLE statement Syntax

CREATE TABLE <table name> (
    <field_name> <data type and size> <one or more constraints>,
    <field_name> <data type and size> <one or more constraints>,
    <field_name> <data type and size> <one or more constraints>,
    ...
    <field_name> <data type and size> <one or more constraints>,
    CONSTRAINT <constraint name> <TYPE> <details>,
    CONSTRAINT <constraint name> <TYPE> <details>,
    CONSTRAINT <constraint name> <TYPE> <details>,
    ...
    CONSTRAINT <constraint name> <TYPE> <details>
);
*/

-- Order of Table Creation 
--   1) tables with no FKs
--   2) tables with FKs to tables already created
--   3) repeat 2 until done

-- PLAYERS
CREATE TABLE w6Players (
    playerID        INT         PRIMARY KEY,
    firstName       VARCHAR(25) NOT NULL,
    lastName        VARCHAR(35) NOT NULL,
    email           VARCHAR(100),
    dob             DATE,
    preferredPosition CHAR(3), 
    CONSTRAINT pref_pos_chk CHECK (preferredPosition IN ('GK','ST','MF','FB', 'SW'))
);

CREATE TABLE w6Teams (
    teamID      INT   GENERATED BY DEFAULT ON NULL AS IDENTITY  PRIMARY KEY,
    teamName    VARCHAR(30) NOT NULL,
    shirtColour VARCHAR(25),
    homeLocation INT,
    maxPlayers  NUMBER(2) DEFAULT 25,
    CONSTRAINT w6Teams_maxPlayers_chk CHECK (maxPlayers BETWEEN 11 AND 25)
);

CREATE TABLE w6Rosters (
    pID    INT,
    tID    INT,
    shirtNumber NUMBER(3) CHECK (shirtNumber < 100),
    pos    CHAR(3),
    CONSTRAINT w6Rosters_w6Players_fk FOREIGN KEY
        (pID) REFERENCES w6Players(playerID),
    CONSTRAINT w6Rosters_pk PRIMARY KEY (pID, tID)
);

-- oops we forgot the FK to the teams table
-- step 1 - check existing data to comply with referential integrity
ALTER TABLE w6Rosters
    ADD CONSTRAINT w6Rosters_w6Teams_fk
        FOREIGN KEY (tID) REFERENCES w6Teams(teamID);
ALTER TABLE w6Rosters
    ADD CONSTRAINT w6Rosters_pos_chk CHECK (pos IN ('GK','ST','MF','FB', 'SW'));


-- DROP
-- order is backwards from CREATE
DROP TABLE w6Rosters CASCADE CONSTRAINTS;
DROP TABLE w6Players CASCADE CONSTRAINTS;
DROP TABLE w6Teams CASCADE CONSTRAINTS;

ALTER TABLE w6Rosters
    DROP CONSTRAINT w6Rosters_pos_chk;
    
-- ---------------
-- DML switch

-- INSERT 
-- LONG FORM 
INSERT INTO w6Players (playerID, firstName, lastName, email, preferredPosition)
    VALUES (1, 'Clint', 'MacDonald', 'clint@sc.ca', 'GK');
    -- any fields (but must include required fields) in any order
SELECT * FROM w6Players;

-- short method
INSERT INTO w6Players VALUES (2, 'Bob', 'McDougall', 'bob@gmail.com', null, null);

-- INSERT with autonumber
INSERT INTO w6Teams VALUES (null, 'Blues', 'Blue', 4, 20);
INSERT INTO w6Teams VALUES (null, 'Red Sox', 'Red', 6, null);

SELECT * FROM w6Teams;

commit;

-- UPDATE
UPDATE w6Players
    SET firstName = 'Robert'
    WHERE playerID = 1;

-- DELETE
DELETE FROM w6Players
    WHERE playerID = 2;

-- Add player 1 to team 1
INSERT INTO w6Rosters VALUES (1, 1, 16, 'GK');
SELECT * FROM w6Players;

SELECT * FROM w6Rosters;

DELETE FROM w6Players WHERE playerID = 1;


